services:
  #############################################################################
  ## Global services
  dev-redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  #############################################################################
  ## Zero node
  subzero-relay-a:
    image: parity/polkadot:v0.9.25
    user: "0:0"
    command:
      - "--alice"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--validator"
      - "--base-path=/tmp/relay/alice"
      - "--chain=/chainspec/rococo-local-raw.json"
      - "--port=30333"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
    volumes:
      - "./node/chainspec:/chainspec"
      - "./node/tmp:/tmp"
    ports:
      - "9944:9944"

  subzero-relay-b:
    image: parity/polkadot:v0.9.25
    user: "0:0"
    command:
      - "--bob"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
      - "--validator"
      - "--base-path=/tmp/relay/bob"
      - "--chain=/chainspec/rococo-local-raw.json"
      - "--port=30333"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/subzero-relay-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    volumes:
      - "./node/chainspec:/chainspec"
      - "./node/tmp:/tmp"
    ports:
      - "9945:9944"

  subzero-parachain-a:
    image: playzero/subzero:3.1.60
    user: "0:0"
    command:
      - "/usr/local/bin/subzero-collator"
      - "--alice"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
      - "--collator"
      - "--force-authoring"
      - "--chain=/chainspec/subzero-parachain-raw.json"
      - "--base-path=/tmp/parachain/alice"
      - "--port=40333"
      - "--ws-port=8844"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
      - "--prometheus-port=9615"
      - "--prometheus-external"
      - "--"
      - "--execution=wasm"
      - "--chain=/chainspec/rococo-local-raw.json"
      - "--port=30343"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
      - "--pruning=archive"
      - "--bootnodes=/dns/subzero-relay-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    volumes:
      - "./node/chainspec:/chainspec"
      - "./node/tmp:/tmp"
    ports:
      - "9954:9944"
      - "9955:8844"
      - "9615:9615"
    depends_on:
      - subzero-relay-a
      - subzero-relay-b

  subzero-parachain-b:
    image: playzero/subzero:3.1.60
    user: "0:0"
    command:
      - "/usr/local/bin/subzero-collator"
      - "--bob"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
      - "--collator"
      - "--force-authoring"
      - "--chain=/chainspec/subzero-parachain-raw.json"
      - "--base-path=/tmp/parachain/bob"
      - "--port=40333"
      - "--ws-port=8844"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
      - "--prometheus-port=9615"
      - "--prometheus-external"
      - "--"
      - "--execution=wasm"
      - "--chain=/chainspec/rococo-local-raw.json"
      - "--port=30343"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/relay-chain-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    volumes:
      - "./node/chainspec:/chainspec"
      - "./node/tmp:/tmp"
    ports:
      - "9956:9944"
      - "9957:8844"
      - "9616:9615"
    depends_on:
      - subzero-relay-a
      - subzero-relay-b

  #############################################################################
  ## Indexer
  indexer-db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  indexer:
    image: subsquid/hydra-indexer:5
    restart: unless-stopped
    environment:
      - WORKERS_NUMBER=2
      - DB_NAME=indexer
      - DB_HOST=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - REDIS_URI=redis://dev-redis:6379/0
      - FORCE_HEIGHT=true
      - BLOCK_HEIGHT=0
      - WS_PROVIDER_ENDPOINT_URI=ws://subzero-parachain-a:8844
    depends_on:
      subzero-relay-a:
        condition: service_started
      subzero-relay-b:
        condition: service_started
      subzero-parachain-a:
        condition: service_started
      indexer-db:
        condition: service_started
      dev-redis:
        condition: service_started
    command: sh -c "yarn db:bootstrap && yarn start:prod"

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:5
    restart: unless-stopped
    depends_on:
      - dev-redis
    environment:
      REDIS_URI: redis://dev-redis:6379/0
      PORT: 8081

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:5
    restart: unless-stopped
    depends_on:
      - dev-redis
      - indexer-db
      - indexer-status-service
      - indexer
    ports:
      - "4010:8080"
    environment:
      - DEV_MODE=true
      - DB_NAME=indexer
      - DB_HOST=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - HYDRA_INDEXER_STATUS_SERVICE=http://indexer-status-service:8081/status

  indexer-ready-state:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y curl && tail -f /dev/null"
    depends_on:
      - indexer-gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://indexer-gateway:8080/console" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #############################################################################
  ## GraphQL / squid

  squid-postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  ## Service
  squid-service:
    build: '../squid'
    volumes:
      - "./config/squid-config.json:/squid/lib/config.json:ro"
    environment:
      DB_HOST: squid-postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      squid-postgres:
        condition: service_started
      indexer-ready-state:
        condition: service_healthy

  gamedao-service-postgres:
    image: postgres:14
    restart: always
    ports:
      - 55322:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  ## GameDAO graph service
  gamedao-graph-service:
    build: '../service'
    environment:
      IPFS_API_URL: "${IPFS_API_URL}"
      IPFS_CLIENT_ID: "${IPFS_CLIENT_ID}"
      IPFS_CLIENT_SECRET: "${IPFS_CLIENT_SECRET}"
      SERVER_PORT: 4000
      CHAIN_RPC_URL: "ws://subzero-parachain-a:8844"
      CHAIN_RPC_URL_OVERRIDE: "ws://localhost:9944"
      DATABASE_URL: "postgresql://postgres:postgres@gamedao-service-postgres:5432/postgres?schema=public"
    depends_on:
      gamedao-service-postgres:
        condition: service_started
      indexer-ready-state:
        condition: service_healthy
    ports:
      - 4090:4000

  ## Hasura
  squid-graphql-engine:
    image: hasura/graphql-engine:latest
    depends_on:
      - "squid-postgres"
      - "squid-service"
      - "gamedao-graph-service"
      - "gamedao-service-postgres"
    restart: always
    ports:
      - 9080:8080
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@squid-postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@squid-postgres:5432/postgres
      PG_SERVICE_DATABASE_URL: postgres://postgres:postgres@gamedao-service-postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "mypassword123"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
