version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  service:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      IPFS_API_URL: https://ipfs.infura.io:5001/api/v0
      IPFS_CLIENT_ID: 1v04L2wj5JmI0JgKF5KztV0oN8o
      IPFS_CLIENT_SECRET: 85547c6003abb67a6335469d1aa6a3a3
      SERVER_PORT: 5000
      CHAIN_RPC_URL: wss://node.dev.para.sub.zero.io
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
