name: API Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the API Docker image
    - uses: actions/checkout@v3
    - run: docker build -t gamedao/api:latest -f packages/api/Dockerfile .
